name: Run Tests

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install dotenv-cli
        run: npm install -g dotenv-cli

      - name: Create .env.test file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_TEST }}" > .env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env.test


      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Database Migrations for Test
        run: npm run migrate:test

      - name: Run TypeScript Check
        run: npm run type-check

      - name: Run Unit Tests
        run: npm run test:unit
